version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "deps(github-actions)"
    schedule:
      interval: "daily"
    target-branch: "main"
