version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "deps(github-actions)"
    schedule:
      interval: "daily"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: "."
    commit-message:
      prefix: "deps(typescript)"
    schedule:
      interval: "monthly"
    target-branch: "main"
    groups:
      typescript:
        patterns:
          - "*"
