name: "Project Status Checker"
description: Check the statuses of urls

runs:
  using: "docker"
  image: docker://ghcr.io/jackplowman/project-status-checker:v1.0.0
  env:
    GITHUB_ACTION: "true"

inputs:
  config_file_path:
    description: "Path to the configuration file, configuration file must be created before running the action"
    required: false
    default: "`github/workspace/status-checker-config.json"
  database_file_path:
    description: "Path to the database file, if file does not exist it will be created"
    required: false
    default: "`github/workspace/status-checker-database.db"
