name: "Project Status Checker"
description: Check the status(s) of urls

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_ACTION: "true"

inputs:
  config_file_path:
    description: "Path to the configuration file, configuration file must be created before running the action"
    required: false
    default: "status-checker-config.json"
  output_file_path:
    description: "Path to the output file, if file does not exist it will be created"
    required: false
    default: "status-checker-output.sqlite"
