# labels auto assigned to PR, keep in sync with labels.yml
documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["README.md", "docs/**"]
dependencies:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["package-lock.json"]
      - head-branch: ["^dependabot"]
typescript:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              ["*.ts", "*.tsx", "**/*.ts", "**/*.tsx", "**/tsconfig.json"]
shell:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["**/*.sh"]
github_actions:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              [".github/workflows/*", ".github/workflows/**/*"]
git-hooks:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["githooks/**"]
